// Generated by `uv run quettos csr-defs` from sw/quettos/isa.py; do not edit.
`ifndef QCORE_CSR_DEFS_SVH
`define QCORE_CSR_DEFS_SVH
`define QCORE_ISA_VERSION 1
`define QCORE_DESC_BYTES 32
`define QCORE_PROGRAM_ALIGN 64
`define QCORE_SREG_COUNT 32
`define QCORE_VSRAM_WORD_ELEMS 8
`define QCORE_META_BYTES 8
`define QCORE_ROPE_ROW_BYTES 128
`define QCORE_ROPE_SHIFT 14
`define QCORE_HEAD_DIM 64
`define QCORE_DUMP_ALIGN 64
`define QCORE_SOFTMAX_FRAC_MIN 16
`define QCORE_SOFTMAX_FRAC_MAX 30
`define QCORE_DESC_OPCODE_LSB 0
`define QCORE_DESC_OPCODE_W 8
`define QCORE_DESC_FLAGS_LSB 8
`define QCORE_DESC_FLAGS_W 8
`define QCORE_DESC_ROW_MASK_LSB 16
`define QCORE_DESC_ROW_MASK_W 8
`define QCORE_DESC_ACCUMULATE_LSB 24
`define QCORE_DESC_ACCUMULATE_W 1
`define QCORE_DESC_UNIT_META_LSB 25
`define QCORE_DESC_UNIT_META_W 1
`define QCORE_DESC_N_FROM_POS_LSB 26
`define QCORE_DESC_N_FROM_POS_W 1
`define QCORE_DESC_K_FROM_POS_LSB 27
`define QCORE_DESC_K_FROM_POS_W 1
`define QCORE_DESC_OUT_MODE_LSB 28
`define QCORE_DESC_OUT_MODE_W 2
`define QCORE_DESC_LEN_FROM_POS_LSB 30
`define QCORE_DESC_LEN_FROM_POS_W 1
`define QCORE_DESC_TRACK_ABSMAX_LSB 31
`define QCORE_DESC_TRACK_ABSMAX_W 1
`define QCORE_DESC_ADDR_A_LSB 32
`define QCORE_DESC_ADDR_A_W 32
`define QCORE_DESC_ADDR_M_LSB 64
`define QCORE_DESC_ADDR_M_W 32
`define QCORE_DESC_N_LSB 96
`define QCORE_DESC_N_W 24
`define QCORE_DESC_K_LSB 120
`define QCORE_DESC_K_W 16
`define QCORE_DESC_VS_SRC_LSB 136
`define QCORE_DESC_VS_SRC_W 16
`define QCORE_DESC_VS_DST_LSB 152
`define QCORE_DESC_VS_DST_W 16
`define QCORE_DESC_VS_AUX_LSB 168
`define QCORE_DESC_VS_AUX_W 16
`define QCORE_DESC_SREG_SRC_LSB 184
`define QCORE_DESC_SREG_SRC_W 8
`define QCORE_DESC_SREG_DST_LSB 192
`define QCORE_DESC_SREG_DST_W 8
`define QCORE_DESC_SRC_ROW_LSB 200
`define QCORE_DESC_SRC_ROW_W 4
`define QCORE_DESC_DST_ROW_LSB 204
`define QCORE_DESC_DST_ROW_W 4
`define QCORE_DESC_SH0_LSB 208
`define QCORE_DESC_SH0_W 8
`define QCORE_DESC_SH1_LSB 216
`define QCORE_DESC_SH1_W 8
`define QCORE_DESC_IMM32_LSB 224
`define QCORE_DESC_IMM32_W 32
`define QCORE_OP_NOP 0
`define QCORE_OP_HALT 1
`define QCORE_OP_GEMV 16
`define QCORE_OP_EMBED 17
`define QCORE_OP_VRMSNORM 32
`define QCORE_OP_VQUANT 33
`define QCORE_OP_VROPE 34
`define QCORE_OP_VSILUMUL 35
`define QCORE_OP_VSOFTMAX 36
`define QCORE_OP_VSUBC 37
`define QCORE_OP_KVWRITE 48
`define QCORE_OP_FENCE 49
`define QCORE_OUT_VSRAM 0
`define QCORE_OUT_ARGMAX 1
`define QCORE_OUT_ARGMAX_DUMP 2
`define QCORE_OUT_VSRAM_DUMP 3
`define QCORE_VQ_W8 1
`define QCORE_VQ_USE_TRACKED 2
`define QCORE_VQ_GROUP 4
`define QCORE_VQ_SCALE_MUL 8
`define QCORE_KVW_TRANSPOSED 1
`define QCORE_CTRL_START 0
`define QCORE_CTRL_STEP 1
`define QCORE_CTRL_ABORT 2
`define QCORE_STATUS_DONE 0
`define QCORE_STATUS_BUSY 1
`define QCORE_STATUS_STEP_HALTED 2
`define QCORE_STATUS_ERR 3
`define QCORE_STATUS_FAULT_LSB 4
`define QCORE_STATUS_FAULT_W 4
`define QCORE_STATUS_FAULT_OP_LSB 8
`define QCORE_STATUS_FAULT_OP_W 8
`define QCORE_FAULT_NONE 0
`define QCORE_FAULT_OPCODE 1
`define QCORE_FAULT_ROW 2
`define QCORE_FAULT_PC_ALIGN 3
`define QCORE_FAULT_CLASS 4
`define QCORE_CSR_WORDS 64
/// w1p: bit 0 START, bit 1 STEP, bit 2 ABORT
`define QCORE_CSR_CTRL 0
/// w1c: bit 0 DONE, bit 1 BUSY, bit 2 STEP_HALTED, bit 3 ERR, [7:4] FAULT, [15:8] FAULT_OP
`define QCORE_CSR_STATUS 1
/// rw: byte address of the next descriptor
`define QCORE_CSR_PC 2
/// rw: bit r enables activation row r
`define QCORE_CSR_ROW_EN 3
/// rw: token id for EMBED
`define QCORE_CSR_TOK 4
/// rw: position of the token
`define QCORE_CSR_POS 5
/// ro: index of the largest ARGMAX-mode output
`define QCORE_CSR_ARGMAX_TOK 6
/// ro: that output (int32)
`define QCORE_CSR_ARGMAX_VAL 7
/// ro: requant saturations
`define QCORE_CSR_SAT_REQ 8
/// ro: vector-unit saturations
`define QCORE_CSR_SAT_VPU 9
/// ro: shifts clamped to [0, 63]
`define QCORE_CSR_ERR_SHIFT 10
/// ro: POS-derived values above their field, VSOFTMAX len outside [1, n], KVWRITE at POS >= k, VSRAM ranges past the end, SREG indices >= 32
`define QCORE_CSR_ERR_BOUNDS 11
/// ro: constant ISA_VERSION
`define QCORE_CSR_ISA_VERSION 12
/// ro: PERF[0] bits [31:0]
`define QCORE_CSR_PERF0_LO 16
/// ro: PERF[0] bits [63:32]
`define QCORE_CSR_PERF0_HI 17
/// ro: PERF[1] bits [31:0]
`define QCORE_CSR_PERF1_LO 18
/// ro: PERF[1] bits [63:32]
`define QCORE_CSR_PERF1_HI 19
/// ro: PERF[2] bits [31:0]
`define QCORE_CSR_PERF2_LO 20
/// ro: PERF[2] bits [63:32]
`define QCORE_CSR_PERF2_HI 21
/// ro: PERF[3] bits [31:0]
`define QCORE_CSR_PERF3_LO 22
/// ro: PERF[3] bits [63:32]
`define QCORE_CSR_PERF3_HI 23
/// ro: PERF[4] bits [31:0]
`define QCORE_CSR_PERF4_LO 24
/// ro: PERF[4] bits [63:32]
`define QCORE_CSR_PERF4_HI 25
/// ro: PERF[5] bits [31:0]
`define QCORE_CSR_PERF5_LO 26
/// ro: PERF[5] bits [63:32]
`define QCORE_CSR_PERF5_HI 27
/// ro: PERF[6] bits [31:0]
`define QCORE_CSR_PERF6_LO 28
/// ro: PERF[6] bits [63:32]
`define QCORE_CSR_PERF6_HI 29
/// ro: PERF[7] bits [31:0]
`define QCORE_CSR_PERF7_LO 30
/// ro: PERF[7] bits [63:32]
`define QCORE_CSR_PERF7_HI 31
/// ro: PERF[8] bits [31:0]
`define QCORE_CSR_PERF8_LO 32
/// ro: PERF[8] bits [63:32]
`define QCORE_CSR_PERF8_HI 33
/// ro: PERF[9] bits [31:0]
`define QCORE_CSR_PERF9_LO 34
/// ro: PERF[9] bits [63:32]
`define QCORE_CSR_PERF9_HI 35
/// ro: PERF[10] bits [31:0]
`define QCORE_CSR_PERF10_LO 36
/// ro: PERF[10] bits [63:32]
`define QCORE_CSR_PERF10_HI 37
/// ro: PERF[11] bits [31:0]
`define QCORE_CSR_PERF11_LO 38
/// ro: PERF[11] bits [63:32]
`define QCORE_CSR_PERF11_HI 39
/// ro: PERF[12] bits [31:0]
`define QCORE_CSR_PERF12_LO 40
/// ro: PERF[12] bits [63:32]
`define QCORE_CSR_PERF12_HI 41
/// ro: PERF[13] bits [31:0]
`define QCORE_CSR_PERF13_LO 42
/// ro: PERF[13] bits [63:32]
`define QCORE_CSR_PERF13_HI 43
/// ro: PERF[14] bits [31:0]
`define QCORE_CSR_PERF14_LO 44
/// ro: PERF[14] bits [63:32]
`define QCORE_CSR_PERF14_HI 45
/// ro: PERF[15] bits [31:0]
`define QCORE_CSR_PERF15_LO 46
/// ro: PERF[15] bits [63:32]
`define QCORE_CSR_PERF15_HI 47
`define QCORE_PERF_BASE 16
`define QCORE_PERF_COUNT 16
`define QCORE_PERF_CYCLES 0
`define QCORE_PERF_BUSY 1
`define QCORE_PERF_MAC_ACTIVE 2
`define QCORE_PERF_STALL_MEM 3
`define QCORE_PERF_STALL_VPU 4
`define QCORE_PERF_STALL_KV 5
`define QCORE_PERF_STALL_SEQ 6
`define QCORE_PERF_STALL_DRAIN 7
`define QCORE_PERF_RD_BEATS 8
`define QCORE_PERF_RD_BYTES 9
`define QCORE_PERF_WT_BYTES 10
`define QCORE_PERF_WR_BEATS 11
`define QCORE_PERF_WR_BYTES 12
`define QCORE_PERF_MACS 13
`define QCORE_PERF_DESCRIPTORS 14
`define QCORE_PERF_FETCH_BEATS 15
`endif
