#!/usr/bin/env bash
# The demo: from a clean clone to text generated by qcore_top.
#
# One command syncs the Python environment, fetches the checkpoint, quantizes
# it to int8, compiles the image and the two descriptor programs, builds the
# Verilator harness and runs the whole model on the RTL, printing every token
# as it leaves the hardware with the cycles it cost and the share of them the
# MAC array was active in.  `quettos demo-report` then prints the summary: the
# ids against the golden model's recorded continuation, the counters a clean
# run leaves at zero, the cycle and utilization table and the wall clock of
# every stage.  Any counter that should be zero and is not fails the run.
#
# Nothing here computes a model value.  The ids are the hardware's, and the
# file they are held to is models/<name>/expected_tokens.json, written by
# `uv run quettos golden <model> --write-expected` and checked in.
#
#   scripts/demo.sh                        the fast model, end to end
#   scripts/demo.sh --model qwen           the headline model
#   scripts/demo.sh --fresh                quantize and compile again
#   scripts/demo.sh -- --lat 200           flags for the harness run
set -euo pipefail
export LC_ALL=C

REPO=$(cd "$(dirname "$0")/.." && pwd -P)
cd "$REPO"

MODEL=smollm2
PROMPT=prompts/chat_short.json
MAX_NEW=20
WB=64
B_MAX=1
VL=4
VSRAM_WORDS=4096
SYNC=1
FRESH=0
PERF=
HARNESS=()

usage() {
  cat <<'USAGE'
usage: scripts/demo.sh [options] [-- harness options]

  --model ALIAS     qwen, smollm2 or a Hugging Face repo id (smollm2)
  --prompt FILE     the prompt compiled into the image; the ids the hardware
                    generates are held to the golden model's record of it
                    (prompts/chat_short.json)
  --max-new N       decode steps; the run stops at an end-of-sequence id (20)
  --wb N            weight-port width, in bytes (64)
  --perf-json PATH  where the harness writes its counters
  --fresh           quantize and compile again even if the outputs are there
  --no-sync         leave the Python environment as it is
  -- ARGS           everything after -- goes to the harness run
USAGE
}

while [ $# -gt 0 ]; do
  case $1 in
    --model) MODEL=$2; shift 2 ;;
    --prompt) PROMPT=$2; shift 2 ;;
    --max-new) MAX_NEW=$2; shift 2 ;;
    --wb) WB=$2; shift 2 ;;
    --perf-json) PERF=$2; shift 2 ;;
    --fresh) FRESH=1; shift ;;
    --no-sync) SYNC=0; shift ;;
    -h|--help) usage; exit 0 ;;
    --) shift; HARNESS=("$@"); break ;;
    *) echo "demo: unknown option $1" >&2; usage >&2; exit 2 ;;
  esac
done

# The summary reads the file the run writes, so the run's --perf-json is the
# script's to set; --perf-json above moves both.
for a in ${HARNESS[@]+"${HARNESS[@]}"}; do
  [ "$a" = "--perf-json" ] || continue
  echo "demo: pass --perf-json to scripts/demo.sh itself, before --" >&2
  exit 2
done

SLUG=$(printf '%s' "$MODEL" | tr 'A-Z/' 'a-z-')
CFG="WB=$WB B_MAX=$B_MAX VL=$VL VSRAM_WORDS=$VSRAM_WORDS"
WORK="build/demo/$SLUG"
STAGES="$WORK/stages.jsonl"
SPEC="$WORK/spec.json"
[ -n "$PERF" ] || PERF="build/perf/demo-$SLUG.json"
mkdir -p "$WORK" "$(dirname "$PERF")"
: > "$STAGES"

# Stage output goes to the terminal; only the `time` keyword's own line is
# captured, so every stage carries the seconds it took into stages.jsonl.
exec 3>&1 4>&2

stage() {
  local name=$1 note=$2
  shift 2
  local secs rc=0
  printf '\n=== %s: %s\n' "$name" "$note" >&3
  TIMEFORMAT=%R
  secs=$( { time "$@" 1>&3 2>&4; } 2>&1 ) || rc=$?
  printf '{"name": "%s", "seconds": %s, "note": "%s"}\n' "$name" "$secs" "$note" >> "$STAGES"
  return $rc
}

reused() {
  printf '\n=== %s: %s\n' "$1" "$2" >&3
  printf '{"name": "%s", "seconds": 0.0, "note": "%s"}\n' "$1" "$2" >> "$STAGES"
}

field() {  # the first value of a top-level key of a JSON object written by json.dumps
  sed -n "s/^ *\"$1\": \"\{0,1\}\([^\",]*\)\"\{0,1\},\{0,1\}$/\1/p" "$2" | head -1
}

download() { uv run quettos download "$MODEL" > "$SPEC"; cat "$SPEC" >&3; }

echo "demo: $MODEL at WB=$WB, prompt $PROMPT, up to $MAX_NEW decode steps"

if [ "$SYNC" = 1 ]; then
  # --inexact: install what the lock names and leave anything else the
  # environment already carries, such as the optional `ref` group.
  stage environment "uv sync --frozen --inexact" uv sync --frozen --inexact
else
  reused environment "the environment as it is (--no-sync)"
fi

stage checkpoint "uv run quettos download $MODEL" download
NAME=$(field name "$SPEC")
[ -n "$NAME" ] || { echo "demo: could not read the model name from $SPEC" >&2; exit 2; }

QUANT="build/quant/$NAME.npz"
if [ "$FRESH" = 1 ] || [ ! -f "$QUANT" ]; then
  stage quantize "uv run quettos quantize $MODEL" uv run quettos quantize "$MODEL"
else
  reused quantize "$QUANT is already built (--fresh rebuilds it)"
fi

IMAGE="build/images/$NAME"
image_ready() {
  [ "$FRESH" = 0 ] || return 1
  [ -f "$IMAGE/layout.json" ] || return 1
  grep -qE "\"wb\": $WB(,|\$)" "$IMAGE/layout.json" || return 1
  grep -q "\"source\": \"$PROMPT\"" "$IMAGE/layout.json" || return 1
}
if image_ready; then
  reused compile "$IMAGE is already compiled for WB=$WB and $PROMPT"
else
  stage compile "uv run quettos compile $MODEL --wb $WB --prompt $PROMPT" \
    uv run quettos compile "$MODEL" --wb "$WB" --prompt "$PROMPT" --out "$IMAGE"
fi

stage harness "make -C sim/verilator build $CFG" make -C sim/verilator build $CFG
# `make -C` turns on -w, so the directory lines land in this capture unless they
# are turned off; -s silences the command echo but not them.
BIN=$(make -s --no-print-directory -C sim/verilator where $CFG)

rc=0
stage run "$(basename "$BIN") --image $IMAGE --max-new $MAX_NEW" \
  "$BIN" --image "$IMAGE" --max-new "$MAX_NEW" --perf-json "$PERF" \
  ${HARNESS[@]+"${HARNESS[@]}"} || rc=$?
if [ "$rc" != 0 ]; then
  echo "demo: the harness exited $rc; the summary below says what it found" >&2
fi
if [ ! -f "$PERF" ]; then
  echo "demo: the harness wrote no $PERF, so there is nothing to summarize" >&2
  exit "${rc:-2}"
fi

if ! uv run quettos demo-report --image "$IMAGE" --perf "$PERF" --stages "$STAGES"; then
  [ "$rc" != 0 ] || rc=1
fi
exit "$rc"
