"""Write the ISA constants of :mod:`quettos.isa` as SystemVerilog and C++ headers.

``uv run quettos csr-defs`` writes ``rtl/qcore_csr_defs.svh`` (one
```define QCORE_<NAME> <value>`` per constant, include-guarded, so a module or
package restates only the constants it uses as ``localparam`` and the file
stays clean under ``verilator -Wall``) and ``sim/verilator/csr_defs.hpp``
(``constexpr uint32_t`` in namespace ``qcore``) from
:func:`quettos.isa.definitions`; ``--check`` regenerates in memory and reports
any difference without writing.  Entry points: :func:`render`, :func:`write`,
:func:`check`.  The register map: ``docs/ISA.md`` (CSR table).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from quettos import isa
from quettos.model import REPO_ROOT

SVH_PATH = REPO_ROOT / "rtl" / "qcore_csr_defs.svh"
HPP_PATH = REPO_ROOT / "sim" / "verilator" / "csr_defs.hpp"
SV_PREFIX = "QCORE_"
SV_GUARD = "QCORE_CSR_DEFS_SVH"
HEADER = "Generated by `uv run quettos csr-defs` from sw/quettos/isa.py; do not edit."


def _csr_comment(name: str) -> str:
    """Bare comment text for a CSR constant (``"ro: ..."``), or ``""`` for other constants."""
    csr = isa.CSR_BY_NAME.get(name[len("CSR_") :]) if name.startswith("CSR_") else None
    return f"{csr.access}: {csr.doc}" if csr is not None else ""


def svh_text() -> str:
    """The SystemVerilog include: one ```define QCORE_<NAME> <value>`` per constant.

    Macros rather than ``localparam`` so that a module or package may include
    the file and use a subset without ``UNUSEDPARAM`` warnings; a CSR macro is
    preceded by a comment line with its access class and meaning.
    """
    lines = [f"// {HEADER}", f"`ifndef {SV_GUARD}", f"`define {SV_GUARD}"]
    for name, value in isa.definitions():
        comment = _csr_comment(name)
        if comment:
            lines.append(f"/// {comment}")
        lines.append(f"`define {SV_PREFIX}{name} {value}")
    lines.append("`endif")
    return "\n".join(lines) + "\n"


def hpp_text() -> str:
    """The C++ header: ``constexpr uint32_t <NAME> = <value>u;`` inside ``namespace qcore``."""
    lines = [f"// {HEADER}", "#pragma once", "#include <cstdint>", "", "namespace qcore {"]
    for name, value in isa.definitions():
        comment = _csr_comment(name)
        tail = f"  // {comment}" if comment else ""
        lines.append(f"constexpr uint32_t {name} = {value}u;{tail}")
    lines += ["}  // namespace qcore"]
    return "\n".join(lines) + "\n"


def render() -> dict[Path, str]:
    """Output path -> generated text for both headers."""
    return {SVH_PATH: svh_text(), HPP_PATH: hpp_text()}


def write() -> list[Path]:
    """Write both headers (creating directories); returns the paths written."""
    out = []
    for path, text in render().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        out.append(path)
    return out


def check() -> dict[Path, str]:
    """Path -> ``ok`` / ``missing`` / ``DIFFERS`` against the checked-in files."""
    status = {}
    for path, text in render().items():
        if not path.exists():
            status[path] = "missing"
        else:
            status[path] = "ok" if path.read_text(encoding="utf-8") == text else "DIFFERS"
    return status


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument(
        "--check", action="store_true", help="compare against the checked-in files; write nothing"
    )
    args = ap.parse_args(argv)
    if args.check:
        status = check()
        for path, s in status.items():
            print(f"{s:8s} {path.relative_to(REPO_ROOT)}")
        return 0 if all(s == "ok" for s in status.values()) else 1
    for path in write():
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
